// apps/company/app/[locale]/trip-requests/new/_components/RouteAndVerificationSection/RouteAndVerificationSection.tsx
'use client';

import React, { useState } from 'react';
import styles from './RouteAndVerificationSection.module.css';

interface RouteAndVerificationSectionProps {
  locale?: string;
}

const translations: Record<string, any> = {
  de: {
    verificationTitle: 'Bestätigungscode bei Abholung:',
    verificationLabel: 'Bestätigungscode:',
    required: 'erforderlich',
    verificationPlaceholder: 'Geben Sie den Bestätigungscode hier ein',
    autoGeneratedBtn: 'Automatisch generieren',
    instructionCalloutTitle: 'Anweisungshinweis:',
    instructionCalloutText: 'Dieser Code überprüft die Identität des Fahrers bei der Abholung. Geben Sie den Code ein oder lassen Sie ihn vom System generieren.',
    routeTitle: 'Routendetails:',
    distanceLabel: 'Entfernung',
    distancePlaceholder: 'Dieses Feld ist nicht anklickbar. Die Entfernung wird automatisch im System berechnet',
    maxDistanceLabel: 'Maximal zulässige Entfernung',
    maxDistancePlaceholder: 'Geben Sie die maximal zulässige Entfernung ein',
    estPeriodLabel: 'Geschätzte Fahrzeit',
    estPeriodPlaceholder: 'Dieses Feld ist nicht anklickbar. Die geschätzte Zeit wird automatisch im System berechnet',
    maxPeriodLabel: 'Maximale Fahrzeit',
    maxPeriodPlaceholder: 'Geben Sie die maximal zulässige Fahrzeit ein',
  },
  en: {
    verificationTitle: 'Pickup Verification Code:',
    verificationLabel: 'Verification Code:',
    required: 'required',
    verificationPlaceholder: 'Write here the Pickup Verification Code',
    autoGeneratedBtn: 'Auto-Generated',
    instructionCalloutTitle: 'Instruction callout:',
    instructionCalloutText: 'This code verifies driver identity at pickup. Enter the code or let the system generate it.',
    routeTitle: 'Route Details:',
    distanceLabel: 'Distance',
    distancePlaceholder: 'This Field is unclickable Just have the Distance Calculated in the System',
    maxDistanceLabel: 'Max Distance Allowed',
    maxDistancePlaceholder: 'Enter the Max Distance Allowed',
    estPeriodLabel: 'EST Driving Period',
    estPeriodPlaceholder: 'This Field is unclickable Just have the EST Time Calculated in the System',
    maxPeriodLabel: 'Max Driving Period',
    maxPeriodPlaceholder: 'Enter the Max Driving Period Allowed',
  },
  fr: {
    verificationTitle: 'Code de vérification au retrait :',
    verificationLabel: 'Code de vérification :',
    required: 'requis',
    verificationPlaceholder: 'Écrivez ici le code de vérification au retrait',
    autoGeneratedBtn: 'Générer automatiquement',
    instructionCalloutTitle: 'Consigne :',
    instructionCalloutText: "Ce code vérifie l'identité du chauffeur lors du retrait. Saisissez le code ou laissez le système le générer.",
    routeTitle: 'Détails de l\'itinéraire :',
    distanceLabel: 'Distance',
    distancePlaceholder: 'Ce champ n\'est pas cliquable. La distance est calculée automatiquement par le système',
    maxDistanceLabel: 'Distance maximale autorisée',
    maxDistancePlaceholder: 'Entrez la distance maximale autorisée',
    estPeriodLabel: 'Temps de conduite estimé',
    estPeriodPlaceholder: 'Ce champ n\'est pas cliquable. Le temps estimé est calculé automatiquement par le système',
    maxPeriodLabel: 'Temps de conduite maximum',
    maxPeriodPlaceholder: 'Entrez le temps de conduite maximum autorisé',
  },
};

export const RouteAndVerificationSection: React.FC<RouteAndVerificationSectionProps> = ({ locale = 'en' }) => {
  const [verificationCode, setVerificationCode] = useState('');
  const [maxDistance, setMaxDistance] = useState('');
  const [maxDrivingPeriod, setMaxDrivingPeriod] = useState('');

  const t = translations[locale] || translations.en;

  const handleAutoGenerate = () => {
    const randomCode = Math.floor(100000 + Math.random() * 900000).toString();
    setVerificationCode(randomCode);
  };

  return (
    <div className={styles['xcar-route-verification-container']}>
      {/* Pickup Verification Code Section */}
      <section className={styles['xcar-section-card']}>
        <h3 className={styles['xcar-section-card__title']}>{t.verificationTitle}</h3>
        
        <div className={styles['xcar-section-card__field']}>
          <div className={styles['xcar-section-card__label-row']}>
            <label className={styles['xcar-section-card__label']}>{t.verificationLabel}</label>
            <span className={styles['xcar-section-card__required']}>{t.required}</span>
          </div>

          <div className={styles['xcar-section-card__input-group']}>
            <input
              type="text"
              className={styles['xcar-section-card__input']}
              placeholder={t.verificationPlaceholder}
              value={verificationCode}
              onChange={(e) => setVerificationCode(e.target.value)}
            />
            <button
              type="button"
              className={styles['xcar-section-card__auto-btn']}
              onClick={handleAutoGenerate}
            >
              {t.autoGeneratedBtn}
            </button>
          </div>
        </div>

        {/* Instruction Callout */}
        <div className={styles['xcar-callout-box']}>
          <div className={styles['xcar-callout-box__icon']}>⚠️</div>
          <div className={styles['xcar-callout-box__content']}>
            <strong className={styles['xcar-callout-box__title']}>{t.instructionCalloutTitle}</strong>
            <p className={styles['xcar-callout-box__text']}>
              {t.instructionCalloutText}
            </p>
          </div>
        </div>
      </section>

      {/* Route Details Section */}
      <section className={styles['xcar-section-card']}>
        <h3 className={styles['xcar-section-card__title']}>{t.routeTitle}</h3>

        <div className={styles['xcar-route-grid']}>
          {/* Distance (Calculated - Unclickable) */}
          <div className={styles['xcar-section-card__field']}>
            <label className={styles['xcar-section-card__label']}>{t.distanceLabel}</label>
            <input
              type="text"
              readOnly
              disabled
              className={`${styles['xcar-section-card__input']} ${styles['xcar-section-card__input--disabled']}`}
              placeholder={t.distancePlaceholder}
            />
          </div>

          {/* Max Distance Allowed */}
          <div className={styles['xcar-section-card__field']}>
            <label className={styles['xcar-section-card__label']}>{t.maxDistanceLabel}</label>
            <div className={styles['xcar-section-card__input-wrapper']}>
              <input
                type="text"
                className={styles['xcar-section-card__input']}
                placeholder={t.maxDistancePlaceholder}
                value={maxDistance}
                onChange={(e) => setMaxDistance(e.target.value)}
              />
              <span className={styles['xcar-section-card__icon']}>📏</span>
            </div>
          </div>

          {/* EST Driving Period (Calculated - Unclickable) */}
          <div className={styles['xcar-section-card__field']}>
            <label className={styles['xcar-section-card__label']}>{t.estPeriodLabel}</label>
            <input
              type="text"
              readOnly
              disabled
              className={`${styles['xcar-section-card__input']} ${styles['xcar-section-card__input--disabled']}`}
              placeholder={t.estPeriodPlaceholder}
            />
          </div>

          {/* Max Driving Period */}
          <div className={styles['xcar-section-card__field']}>
            <label className={styles['xcar-section-card__label']}>{t.maxPeriodLabel}</label>
            <div className={styles['xcar-section-card__input-wrapper']}>
              <input
                type="text"
                className={styles['xcar-section-card__input']}
                placeholder={t.maxPeriodPlaceholder}
                value={maxDrivingPeriod}
                onChange={(e) => setMaxDrivingPeriod(e.target.value)}
              />
              <span className={styles['xcar-section-card__icon']}>⏱️</span>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default RouteAndVerificationSection;